name: Generate images.json

on:
  push:
    paths:
      - "art/mainGallery/**"
      - ".github/workflow/generate-images-json.ym"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate images.json
        run: |
          echo "[" > images.json
          find images -type f -printf '  "%P",\n' | sed '$ s/,$//' >> images.json
          echo "]" >> images.json

      - name: Commit images.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images.json
          git commit -m "Update images.json" || echo "No changes to commit"
          git push
